-- MySQL Script generated by MySQL Workbench
-- Sat Oct 11 23:11:56 2014
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema hhgg853478196
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hhgg853478196` DEFAULT CHARACTER SET utf8 ;
USE `hhgg853478196` ;

-- -----------------------------------------------------
-- Table `hhgg853478196`.`manager`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hhgg853478196`.`manager` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `type` TINYINT NULL,
  PRIMARY KEY (`id`),
  INDEX `idx_name_password` (`name` ASC, `password` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hhgg853478196`.`history`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hhgg853478196`.`history` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NULL,
  `time` DATETIME NULL,
  `description_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `idx_time` (`time` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hhgg853478196`.`description`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hhgg853478196`.`description` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `text` TEXT NULL,
  `type` TINYINT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hhgg853478196`.`picture`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hhgg853478196`.`picture` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `path` VARCHAR(250) NULL,
  `type` TINYINT NULL,
  `description_id` INT NULL,
  `time_stamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `idx_time` (`time_stamp` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hhgg853478196`.`example`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hhgg853478196`.`example` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `description_id` INT NULL,
  `time_stamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `idx_time` (`time_stamp` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hhgg853478196`.`recruit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hhgg853478196`.`recruit` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `position` VARCHAR(45) NULL,
  `require_count` INT NULL,
  `location` VARCHAR(45) NULL,
  `ability` VARCHAR(250) NULL,
  `education` VARCHAR(45) NULL,
  `salary` VARCHAR(45) NULL,
  `description_id` INT NULL,
  `begin_time` DATETIME NULL,
  `end_time` DATETIME NULL,
  `time_stamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `idx_time` (`time_stamp` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hhgg853478196`.`example_group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hhgg853478196`.`example_group` (
  `picture_id` INT NULL,
  `example_id` INT NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hhgg853478196`.`config`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hhgg853478196`.`config` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `type` TINYINT NULL,
  `content` VARCHAR(250) NULL,
  `description_id` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hhgg853478196`.`message`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hhgg853478196`.`message` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `email` VARCHAR(100) NULL,
  `phone` VARCHAR(20) NULL,
  `content` VARCHAR(250) NULL,
  `status` TINYINT NULL,
  `time_stamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `idx_time` (`time_stamp` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `hhgg853478196`.`manager`
-- -----------------------------------------------------
START TRANSACTION;
USE `hhgg853478196`;
INSERT INTO `hhgg853478196`.`manager` (`id`, `name`, `password`, `type`) VALUES (1, 'admin', 'admin', 0);

COMMIT;

