-- MySQL Script generated by MySQL Workbench
-- Sat Oct 11 20:08:17 2014
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema hg
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `hg` ;
CREATE SCHEMA IF NOT EXISTS `hg` DEFAULT CHARACTER SET utf8 ;
USE `hg` ;

-- -----------------------------------------------------
-- Table `hg`.`manager`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hg`.`manager` ;

CREATE TABLE IF NOT EXISTS `hg`.`manager` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `type` TINYINT NULL,
  PRIMARY KEY (`id`),
  INDEX `idx_name_password` (`name` ASC, `password` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hg`.`history`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hg`.`history` ;

CREATE TABLE IF NOT EXISTS `hg`.`history` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NULL,
  `time` DATETIME NULL,
  `description_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `idx_time` (`time` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hg`.`description`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hg`.`description` ;

CREATE TABLE IF NOT EXISTS `hg`.`description` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `text` TEXT NULL,
  `type` TINYINT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hg`.`picture`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hg`.`picture` ;

CREATE TABLE IF NOT EXISTS `hg`.`picture` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `path` VARCHAR(250) NULL,
  `type` TINYINT NULL,
  `description_id` INT NULL,
  `time_stamp` TIMESTAMP NULL DEFAULT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `idx_time` (`time_stamp` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hg`.`example`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hg`.`example` ;

CREATE TABLE IF NOT EXISTS `hg`.`example` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `description_id` INT NULL,
  `time_stamp` TIMESTAMP NULL DEFAULT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `idx_time` (`time_stamp` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hg`.`recruit`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hg`.`recruit` ;

CREATE TABLE IF NOT EXISTS `hg`.`recruit` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `position` VARCHAR(45) NULL,
  `require_count` INT NULL,
  `location` VARCHAR(45) NULL,
  `ability` VARCHAR(250) NULL,
  `education` VARCHAR(45) NULL,
  `salary` VARCHAR(45) NULL,
  `description_id` INT NULL,
  `begin_time` DATETIME NULL,
  `end_time` DATETIME NULL,
  `time_stamp` TIMESTAMP NULL DEFAULT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `idx_time` (`time_stamp` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hg`.`example_group`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hg`.`example_group` ;

CREATE TABLE IF NOT EXISTS `hg`.`example_group` (
  `picture_id` INT NULL,
  `example_id` INT NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hg`.`config`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hg`.`config` ;

CREATE TABLE IF NOT EXISTS `hg`.`config` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `type` TINYINT NULL,
  `content` VARCHAR(250) NULL,
  `description_id` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hg`.`message`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hg`.`message` ;

CREATE TABLE IF NOT EXISTS `hg`.`message` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `email` VARCHAR(100) NULL,
  `phone` VARCHAR(20) NULL,
  `content` VARCHAR(250) NULL,
  `status` TINYINT NULL,
  `time_stamp` TIMESTAMP NULL DEFAULT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `idx_time` (`time_stamp` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `hg`.`manager`
-- -----------------------------------------------------
START TRANSACTION;
USE `hg`;
INSERT INTO `hg`.`manager` (`id`, `name`, `password`, `type`) VALUES (1, 'admin', 'admin', 0);

COMMIT;

