/**
 * This class is generated by jOOQ
 */
package cn.hg.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DealIds extends org.jooq.impl.TableImpl<cn.hg.jooq.tables.records.DealIdsRecord> {

	private static final long serialVersionUID = -1852407027;

	/**
	 * The singleton instance of <code>test.deal_ids</code>
	 */
	public static final cn.hg.jooq.tables.DealIds DEAL_IDS = new cn.hg.jooq.tables.DealIds();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<cn.hg.jooq.tables.records.DealIdsRecord> getRecordType() {
		return cn.hg.jooq.tables.records.DealIdsRecord.class;
	}

	/**
	 * The column <code>test.deal_ids.deal_id</code>.
	 */
	public final org.jooq.TableField<cn.hg.jooq.tables.records.DealIdsRecord, java.lang.Integer> DEAL_ID = createField("deal_id", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * Create a <code>test.deal_ids</code> table reference
	 */
	public DealIds() {
		this("deal_ids", null);
	}

	/**
	 * Create an aliased <code>test.deal_ids</code> table reference
	 */
	public DealIds(java.lang.String alias) {
		this(alias, cn.hg.jooq.tables.DealIds.DEAL_IDS);
	}

	private DealIds(java.lang.String alias, org.jooq.Table<cn.hg.jooq.tables.records.DealIdsRecord> aliased) {
		this(alias, aliased, null);
	}

	private DealIds(java.lang.String alias, org.jooq.Table<cn.hg.jooq.tables.records.DealIdsRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, cn.hg.jooq.Test.TEST, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public cn.hg.jooq.tables.DealIds as(java.lang.String alias) {
		return new cn.hg.jooq.tables.DealIds(alias, this);
	}

	/**
	 * Rename this table
	 */
	public cn.hg.jooq.tables.DealIds rename(java.lang.String name) {
		return new cn.hg.jooq.tables.DealIds(name, null);
	}
}
