/**
 * This class is generated by jOOQ
 */
package cn.hg.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ExampleGroup extends org.jooq.impl.TableImpl<cn.hg.jooq.tables.records.ExampleGroupRecord> {

	private static final long serialVersionUID = -1152394667;

	/**
	 * The singleton instance of <code>hg.example_group</code>
	 */
	public static final cn.hg.jooq.tables.ExampleGroup EXAMPLE_GROUP = new cn.hg.jooq.tables.ExampleGroup();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<cn.hg.jooq.tables.records.ExampleGroupRecord> getRecordType() {
		return cn.hg.jooq.tables.records.ExampleGroupRecord.class;
	}

	/**
	 * The column <code>hg.example_group.picture_id</code>.
	 */
	public final org.jooq.TableField<cn.hg.jooq.tables.records.ExampleGroupRecord, java.lang.Integer> PICTURE_ID = createField("picture_id", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>hg.example_group.example_id</code>.
	 */
	public final org.jooq.TableField<cn.hg.jooq.tables.records.ExampleGroupRecord, java.lang.Integer> EXAMPLE_ID = createField("example_id", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * Create a <code>hg.example_group</code> table reference
	 */
	public ExampleGroup() {
		this("example_group", null);
	}

	/**
	 * Create an aliased <code>hg.example_group</code> table reference
	 */
	public ExampleGroup(java.lang.String alias) {
		this(alias, cn.hg.jooq.tables.ExampleGroup.EXAMPLE_GROUP);
	}

	private ExampleGroup(java.lang.String alias, org.jooq.Table<cn.hg.jooq.tables.records.ExampleGroupRecord> aliased) {
		this(alias, aliased, null);
	}

	private ExampleGroup(java.lang.String alias, org.jooq.Table<cn.hg.jooq.tables.records.ExampleGroupRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, cn.hg.jooq.Hg.HG, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public cn.hg.jooq.tables.ExampleGroup as(java.lang.String alias) {
		return new cn.hg.jooq.tables.ExampleGroup(alias, this);
	}

	/**
	 * Rename this table
	 */
	public cn.hg.jooq.tables.ExampleGroup rename(java.lang.String name) {
		return new cn.hg.jooq.tables.ExampleGroup(name, null);
	}
}
