/**
 * This class is generated by jOOQ
 */
package cn.hg.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Example extends org.jooq.impl.TableImpl<cn.hg.jooq.tables.records.ExampleRecord> {

	private static final long serialVersionUID = -1520316543;

	/**
	 * The singleton instance of <code>hg.example</code>
	 */
	public static final cn.hg.jooq.tables.Example EXAMPLE = new cn.hg.jooq.tables.Example();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<cn.hg.jooq.tables.records.ExampleRecord> getRecordType() {
		return cn.hg.jooq.tables.records.ExampleRecord.class;
	}

	/**
	 * The column <code>hg.example.id</code>.
	 */
	public final org.jooq.TableField<cn.hg.jooq.tables.records.ExampleRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>hg.example.name</code>.
	 */
	public final org.jooq.TableField<cn.hg.jooq.tables.records.ExampleRecord, java.lang.String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(45), this, "");

	/**
	 * The column <code>hg.example.description_id</code>.
	 */
	public final org.jooq.TableField<cn.hg.jooq.tables.records.ExampleRecord, java.lang.Integer> DESCRIPTION_ID = createField("description_id", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>hg.example.time_stamp</code>.
	 */
	public final org.jooq.TableField<cn.hg.jooq.tables.records.ExampleRecord, java.sql.Timestamp> TIME_STAMP = createField("time_stamp", org.jooq.impl.SQLDataType.TIMESTAMP.defaulted(true), this, "");

	/**
	 * Create a <code>hg.example</code> table reference
	 */
	public Example() {
		this("example", null);
	}

	/**
	 * Create an aliased <code>hg.example</code> table reference
	 */
	public Example(java.lang.String alias) {
		this(alias, cn.hg.jooq.tables.Example.EXAMPLE);
	}

	private Example(java.lang.String alias, org.jooq.Table<cn.hg.jooq.tables.records.ExampleRecord> aliased) {
		this(alias, aliased, null);
	}

	private Example(java.lang.String alias, org.jooq.Table<cn.hg.jooq.tables.records.ExampleRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, cn.hg.jooq.Hg.HG, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<cn.hg.jooq.tables.records.ExampleRecord, java.lang.Integer> getIdentity() {
		return cn.hg.jooq.Keys.IDENTITY_EXAMPLE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<cn.hg.jooq.tables.records.ExampleRecord> getPrimaryKey() {
		return cn.hg.jooq.Keys.KEY_EXAMPLE_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<cn.hg.jooq.tables.records.ExampleRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<cn.hg.jooq.tables.records.ExampleRecord>>asList(cn.hg.jooq.Keys.KEY_EXAMPLE_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public cn.hg.jooq.tables.Example as(java.lang.String alias) {
		return new cn.hg.jooq.tables.Example(alias, this);
	}

	/**
	 * Rename this table
	 */
	public cn.hg.jooq.tables.Example rename(java.lang.String name) {
		return new cn.hg.jooq.tables.Example(name, null);
	}
}
