/**
 * This class is generated by jOOQ
 */
package cn.hg.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Manager extends org.jooq.impl.TableImpl<cn.hg.jooq.tables.records.ManagerRecord> {

	private static final long serialVersionUID = -1019406753;

	/**
	 * The singleton instance of <code>hg.manager</code>
	 */
	public static final cn.hg.jooq.tables.Manager MANAGER = new cn.hg.jooq.tables.Manager();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<cn.hg.jooq.tables.records.ManagerRecord> getRecordType() {
		return cn.hg.jooq.tables.records.ManagerRecord.class;
	}

	/**
	 * The column <code>hg.manager.id</code>.
	 */
	public final org.jooq.TableField<cn.hg.jooq.tables.records.ManagerRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>hg.manager.name</code>.
	 */
	public final org.jooq.TableField<cn.hg.jooq.tables.records.ManagerRecord, java.lang.String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(45).nullable(false), this, "");

	/**
	 * The column <code>hg.manager.password</code>.
	 */
	public final org.jooq.TableField<cn.hg.jooq.tables.records.ManagerRecord, java.lang.String> PASSWORD = createField("password", org.jooq.impl.SQLDataType.VARCHAR.length(45).nullable(false), this, "");

	/**
	 * The column <code>hg.manager.type</code>.
	 */
	public final org.jooq.TableField<cn.hg.jooq.tables.records.ManagerRecord, java.lang.Byte> TYPE = createField("type", org.jooq.impl.SQLDataType.TINYINT, this, "");

	/**
	 * Create a <code>hg.manager</code> table reference
	 */
	public Manager() {
		this("manager", null);
	}

	/**
	 * Create an aliased <code>hg.manager</code> table reference
	 */
	public Manager(java.lang.String alias) {
		this(alias, cn.hg.jooq.tables.Manager.MANAGER);
	}

	private Manager(java.lang.String alias, org.jooq.Table<cn.hg.jooq.tables.records.ManagerRecord> aliased) {
		this(alias, aliased, null);
	}

	private Manager(java.lang.String alias, org.jooq.Table<cn.hg.jooq.tables.records.ManagerRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, cn.hg.jooq.Hg.HG, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<cn.hg.jooq.tables.records.ManagerRecord, java.lang.Integer> getIdentity() {
		return cn.hg.jooq.Keys.IDENTITY_MANAGER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<cn.hg.jooq.tables.records.ManagerRecord> getPrimaryKey() {
		return cn.hg.jooq.Keys.KEY_MANAGER_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<cn.hg.jooq.tables.records.ManagerRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<cn.hg.jooq.tables.records.ManagerRecord>>asList(cn.hg.jooq.Keys.KEY_MANAGER_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public cn.hg.jooq.tables.Manager as(java.lang.String alias) {
		return new cn.hg.jooq.tables.Manager(alias, this);
	}

	/**
	 * Rename this table
	 */
	public cn.hg.jooq.tables.Manager rename(java.lang.String name) {
		return new cn.hg.jooq.tables.Manager(name, null);
	}
}
