/**
 * This class is generated by jOOQ
 */
package cn.hg.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Message extends org.jooq.impl.TableImpl<cn.hg.jooq.tables.records.MessageRecord> {

	private static final long serialVersionUID = 1106023810;

	/**
	 * The singleton instance of <code>hg.message</code>
	 */
	public static final cn.hg.jooq.tables.Message MESSAGE = new cn.hg.jooq.tables.Message();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<cn.hg.jooq.tables.records.MessageRecord> getRecordType() {
		return cn.hg.jooq.tables.records.MessageRecord.class;
	}

	/**
	 * The column <code>hg.message.id</code>.
	 */
	public final org.jooq.TableField<cn.hg.jooq.tables.records.MessageRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>hg.message.name</code>.
	 */
	public final org.jooq.TableField<cn.hg.jooq.tables.records.MessageRecord, java.lang.String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(45), this, "");

	/**
	 * The column <code>hg.message.email</code>.
	 */
	public final org.jooq.TableField<cn.hg.jooq.tables.records.MessageRecord, java.lang.String> EMAIL = createField("email", org.jooq.impl.SQLDataType.VARCHAR.length(100), this, "");

	/**
	 * The column <code>hg.message.phone</code>.
	 */
	public final org.jooq.TableField<cn.hg.jooq.tables.records.MessageRecord, java.lang.String> PHONE = createField("phone", org.jooq.impl.SQLDataType.VARCHAR.length(20), this, "");

	/**
	 * The column <code>hg.message.content</code>.
	 */
	public final org.jooq.TableField<cn.hg.jooq.tables.records.MessageRecord, java.lang.String> CONTENT = createField("content", org.jooq.impl.SQLDataType.VARCHAR.length(250), this, "");

	/**
	 * The column <code>hg.message.status</code>.
	 */
	public final org.jooq.TableField<cn.hg.jooq.tables.records.MessageRecord, cn.hg.constant.ConstantGenerator.Constant> STATUS = createField("status", org.jooq.impl.SQLDataType.TINYINT, this, "", new cn.hg.extend.jooq.ConstantConverter(java.lang.Byte.class, cn.hg.constant.MessageStatus.class));

	/**
	 * The column <code>hg.message.time_stamp</code>.
	 */
	public final org.jooq.TableField<cn.hg.jooq.tables.records.MessageRecord, java.sql.Timestamp> TIME_STAMP = createField("time_stamp", org.jooq.impl.SQLDataType.TIMESTAMP.defaulted(true), this, "");

	/**
	 * Create a <code>hg.message</code> table reference
	 */
	public Message() {
		this("message", null);
	}

	/**
	 * Create an aliased <code>hg.message</code> table reference
	 */
	public Message(java.lang.String alias) {
		this(alias, cn.hg.jooq.tables.Message.MESSAGE);
	}

	private Message(java.lang.String alias, org.jooq.Table<cn.hg.jooq.tables.records.MessageRecord> aliased) {
		this(alias, aliased, null);
	}

	private Message(java.lang.String alias, org.jooq.Table<cn.hg.jooq.tables.records.MessageRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, cn.hg.jooq.Hg.HG, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<cn.hg.jooq.tables.records.MessageRecord, java.lang.Integer> getIdentity() {
		return cn.hg.jooq.Keys.IDENTITY_MESSAGE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<cn.hg.jooq.tables.records.MessageRecord> getPrimaryKey() {
		return cn.hg.jooq.Keys.KEY_MESSAGE_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<cn.hg.jooq.tables.records.MessageRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<cn.hg.jooq.tables.records.MessageRecord>>asList(cn.hg.jooq.Keys.KEY_MESSAGE_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public cn.hg.jooq.tables.Message as(java.lang.String alias) {
		return new cn.hg.jooq.tables.Message(alias, this);
	}

	/**
	 * Rename this table
	 */
	public cn.hg.jooq.tables.Message rename(java.lang.String name) {
		return new cn.hg.jooq.tables.Message(name, null);
	}
}
