/**
 * This class is generated by jOOQ
 */
package cn.hg.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MobileDeal extends org.jooq.impl.TableImpl<cn.hg.jooq.tables.records.MobileDealRecord> {

	private static final long serialVersionUID = 42934387;

	/**
	 * The singleton instance of <code>test.mobile_deal</code>
	 */
	public static final cn.hg.jooq.tables.MobileDeal MOBILE_DEAL = new cn.hg.jooq.tables.MobileDeal();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<cn.hg.jooq.tables.records.MobileDealRecord> getRecordType() {
		return cn.hg.jooq.tables.records.MobileDealRecord.class;
	}

	/**
	 * The column <code>test.mobile_deal.mobile</code>.
	 */
	public final org.jooq.TableField<cn.hg.jooq.tables.records.MobileDealRecord, java.lang.String> MOBILE = createField("mobile", org.jooq.impl.SQLDataType.VARCHAR.length(45), this, "");

	/**
	 * The column <code>test.mobile_deal.deal_id</code>.
	 */
	public final org.jooq.TableField<cn.hg.jooq.tables.records.MobileDealRecord, java.lang.Integer> DEAL_ID = createField("deal_id", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * Create a <code>test.mobile_deal</code> table reference
	 */
	public MobileDeal() {
		this("mobile_deal", null);
	}

	/**
	 * Create an aliased <code>test.mobile_deal</code> table reference
	 */
	public MobileDeal(java.lang.String alias) {
		this(alias, cn.hg.jooq.tables.MobileDeal.MOBILE_DEAL);
	}

	private MobileDeal(java.lang.String alias, org.jooq.Table<cn.hg.jooq.tables.records.MobileDealRecord> aliased) {
		this(alias, aliased, null);
	}

	private MobileDeal(java.lang.String alias, org.jooq.Table<cn.hg.jooq.tables.records.MobileDealRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, cn.hg.jooq.Test.TEST, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public cn.hg.jooq.tables.MobileDeal as(java.lang.String alias) {
		return new cn.hg.jooq.tables.MobileDeal(alias, this);
	}

	/**
	 * Rename this table
	 */
	public cn.hg.jooq.tables.MobileDeal rename(java.lang.String name) {
		return new cn.hg.jooq.tables.MobileDeal(name, null);
	}
}
