/**
 * This class is generated by jOOQ
 */
package cn.hg.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Picture extends org.jooq.impl.TableImpl<cn.hg.jooq.tables.records.PictureRecord> {

	private static final long serialVersionUID = -1215843967;

	/**
	 * The singleton instance of <code>hg.picture</code>
	 */
	public static final cn.hg.jooq.tables.Picture PICTURE = new cn.hg.jooq.tables.Picture();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<cn.hg.jooq.tables.records.PictureRecord> getRecordType() {
		return cn.hg.jooq.tables.records.PictureRecord.class;
	}

	/**
	 * The column <code>hg.picture.id</code>.
	 */
	public final org.jooq.TableField<cn.hg.jooq.tables.records.PictureRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>hg.picture.name</code>.
	 */
	public final org.jooq.TableField<cn.hg.jooq.tables.records.PictureRecord, java.lang.String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(45), this, "");

	/**
	 * The column <code>hg.picture.path</code>.
	 */
	public final org.jooq.TableField<cn.hg.jooq.tables.records.PictureRecord, java.lang.String> PATH = createField("path", org.jooq.impl.SQLDataType.VARCHAR.length(250), this, "");

	/**
	 * The column <code>hg.picture.type</code>.
	 */
	public final org.jooq.TableField<cn.hg.jooq.tables.records.PictureRecord, java.lang.Byte> TYPE = createField("type", org.jooq.impl.SQLDataType.TINYINT, this, "");

	/**
	 * The column <code>hg.picture.description_id</code>.
	 */
	public final org.jooq.TableField<cn.hg.jooq.tables.records.PictureRecord, java.lang.Integer> DESCRIPTION_ID = createField("description_id", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>hg.picture.time_stamp</code>.
	 */
	public final org.jooq.TableField<cn.hg.jooq.tables.records.PictureRecord, java.sql.Timestamp> TIME_STAMP = createField("time_stamp", org.jooq.impl.SQLDataType.TIMESTAMP.defaulted(true), this, "");

	/**
	 * Create a <code>hg.picture</code> table reference
	 */
	public Picture() {
		this("picture", null);
	}

	/**
	 * Create an aliased <code>hg.picture</code> table reference
	 */
	public Picture(java.lang.String alias) {
		this(alias, cn.hg.jooq.tables.Picture.PICTURE);
	}

	private Picture(java.lang.String alias, org.jooq.Table<cn.hg.jooq.tables.records.PictureRecord> aliased) {
		this(alias, aliased, null);
	}

	private Picture(java.lang.String alias, org.jooq.Table<cn.hg.jooq.tables.records.PictureRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, cn.hg.jooq.Hg.HG, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<cn.hg.jooq.tables.records.PictureRecord, java.lang.Integer> getIdentity() {
		return cn.hg.jooq.Keys.IDENTITY_PICTURE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<cn.hg.jooq.tables.records.PictureRecord> getPrimaryKey() {
		return cn.hg.jooq.Keys.KEY_PICTURE_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<cn.hg.jooq.tables.records.PictureRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<cn.hg.jooq.tables.records.PictureRecord>>asList(cn.hg.jooq.Keys.KEY_PICTURE_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public cn.hg.jooq.tables.Picture as(java.lang.String alias) {
		return new cn.hg.jooq.tables.Picture(alias, this);
	}

	/**
	 * Rename this table
	 */
	public cn.hg.jooq.tables.Picture rename(java.lang.String name) {
		return new cn.hg.jooq.tables.Picture(name, null);
	}
}
