/**
 * This class is generated by jOOQ
 */
package cn.hg.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Recruit extends org.jooq.impl.TableImpl<cn.hg.jooq.tables.records.RecruitRecord> {

	private static final long serialVersionUID = 1187276365;

	/**
	 * The singleton instance of <code>hg.recruit</code>
	 */
	public static final cn.hg.jooq.tables.Recruit RECRUIT = new cn.hg.jooq.tables.Recruit();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<cn.hg.jooq.tables.records.RecruitRecord> getRecordType() {
		return cn.hg.jooq.tables.records.RecruitRecord.class;
	}

	/**
	 * The column <code>hg.recruit.id</code>.
	 */
	public final org.jooq.TableField<cn.hg.jooq.tables.records.RecruitRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>hg.recruit.position</code>.
	 */
	public final org.jooq.TableField<cn.hg.jooq.tables.records.RecruitRecord, java.lang.String> POSITION = createField("position", org.jooq.impl.SQLDataType.VARCHAR.length(45), this, "");

	/**
	 * The column <code>hg.recruit.require_count</code>.
	 */
	public final org.jooq.TableField<cn.hg.jooq.tables.records.RecruitRecord, java.lang.Integer> REQUIRE_COUNT = createField("require_count", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>hg.recruit.location</code>.
	 */
	public final org.jooq.TableField<cn.hg.jooq.tables.records.RecruitRecord, java.lang.String> LOCATION = createField("location", org.jooq.impl.SQLDataType.VARCHAR.length(45), this, "");

	/**
	 * The column <code>hg.recruit.ability</code>.
	 */
	public final org.jooq.TableField<cn.hg.jooq.tables.records.RecruitRecord, java.lang.String> ABILITY = createField("ability", org.jooq.impl.SQLDataType.CLOB.length(65535), this, "");

	/**
	 * The column <code>hg.recruit.education</code>.
	 */
	public final org.jooq.TableField<cn.hg.jooq.tables.records.RecruitRecord, java.lang.String> EDUCATION = createField("education", org.jooq.impl.SQLDataType.VARCHAR.length(45), this, "");

	/**
	 * The column <code>hg.recruit.salary</code>.
	 */
	public final org.jooq.TableField<cn.hg.jooq.tables.records.RecruitRecord, java.lang.String> SALARY = createField("salary", org.jooq.impl.SQLDataType.VARCHAR.length(45), this, "");

	/**
	 * The column <code>hg.recruit.description_id</code>.
	 */
	public final org.jooq.TableField<cn.hg.jooq.tables.records.RecruitRecord, java.lang.Integer> DESCRIPTION_ID = createField("description_id", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>hg.recruit.begin_time</code>.
	 */
	public final org.jooq.TableField<cn.hg.jooq.tables.records.RecruitRecord, java.sql.Timestamp> BEGIN_TIME = createField("begin_time", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

	/**
	 * The column <code>hg.recruit.end_time</code>.
	 */
	public final org.jooq.TableField<cn.hg.jooq.tables.records.RecruitRecord, java.sql.Timestamp> END_TIME = createField("end_time", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

	/**
	 * The column <code>hg.recruit.time_stamp</code>.
	 */
	public final org.jooq.TableField<cn.hg.jooq.tables.records.RecruitRecord, java.sql.Timestamp> TIME_STAMP = createField("time_stamp", org.jooq.impl.SQLDataType.TIMESTAMP.defaulted(true), this, "");

	/**
	 * The column <code>hg.recruit.apply</code>.
	 */
	public final org.jooq.TableField<cn.hg.jooq.tables.records.RecruitRecord, java.lang.String> APPLY = createField("apply", org.jooq.impl.SQLDataType.VARCHAR.length(1000), this, "");

	/**
	 * Create a <code>hg.recruit</code> table reference
	 */
	public Recruit() {
		this("recruit", null);
	}

	/**
	 * Create an aliased <code>hg.recruit</code> table reference
	 */
	public Recruit(java.lang.String alias) {
		this(alias, cn.hg.jooq.tables.Recruit.RECRUIT);
	}

	private Recruit(java.lang.String alias, org.jooq.Table<cn.hg.jooq.tables.records.RecruitRecord> aliased) {
		this(alias, aliased, null);
	}

	private Recruit(java.lang.String alias, org.jooq.Table<cn.hg.jooq.tables.records.RecruitRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, cn.hg.jooq.Hg.HG, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<cn.hg.jooq.tables.records.RecruitRecord, java.lang.Integer> getIdentity() {
		return cn.hg.jooq.Keys.IDENTITY_RECRUIT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<cn.hg.jooq.tables.records.RecruitRecord> getPrimaryKey() {
		return cn.hg.jooq.Keys.KEY_RECRUIT_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<cn.hg.jooq.tables.records.RecruitRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<cn.hg.jooq.tables.records.RecruitRecord>>asList(cn.hg.jooq.Keys.KEY_RECRUIT_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public cn.hg.jooq.tables.Recruit as(java.lang.String alias) {
		return new cn.hg.jooq.tables.Recruit(alias, this);
	}

	/**
	 * Rename this table
	 */
	public cn.hg.jooq.tables.Recruit rename(java.lang.String name) {
		return new cn.hg.jooq.tables.Recruit(name, null);
	}
}
