/**
 * This class is generated by jOOQ
 */
package cn.hg.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Test extends org.jooq.impl.TableImpl<cn.hg.jooq.tables.records.TestRecord> {

	private static final long serialVersionUID = 2044758834;

	/**
	 * The singleton instance of <code>test.test</code>
	 */
	public static final cn.hg.jooq.tables.Test TEST = new cn.hg.jooq.tables.Test();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<cn.hg.jooq.tables.records.TestRecord> getRecordType() {
		return cn.hg.jooq.tables.records.TestRecord.class;
	}

	/**
	 * The column <code>test.test.id</code>.
	 */
	public final org.jooq.TableField<cn.hg.jooq.tables.records.TestRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>test.test.name</code>.
	 */
	public final org.jooq.TableField<cn.hg.jooq.tables.records.TestRecord, java.lang.String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(45), this, "");

	/**
	 * Create a <code>test.test</code> table reference
	 */
	public Test() {
		this("test", null);
	}

	/**
	 * Create an aliased <code>test.test</code> table reference
	 */
	public Test(java.lang.String alias) {
		this(alias, cn.hg.jooq.tables.Test.TEST);
	}

	private Test(java.lang.String alias, org.jooq.Table<cn.hg.jooq.tables.records.TestRecord> aliased) {
		this(alias, aliased, null);
	}

	private Test(java.lang.String alias, org.jooq.Table<cn.hg.jooq.tables.records.TestRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, cn.hg.jooq.Test.TEST, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<cn.hg.jooq.tables.records.TestRecord, java.lang.Integer> getIdentity() {
		return cn.hg.jooq.Keys.IDENTITY_TEST;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<cn.hg.jooq.tables.records.TestRecord> getPrimaryKey() {
		return cn.hg.jooq.Keys.KEY_TEST_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<cn.hg.jooq.tables.records.TestRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<cn.hg.jooq.tables.records.TestRecord>>asList(cn.hg.jooq.Keys.KEY_TEST_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public cn.hg.jooq.tables.Test as(java.lang.String alias) {
		return new cn.hg.jooq.tables.Test(alias, this);
	}

	/**
	 * Rename this table
	 */
	public cn.hg.jooq.tables.Test rename(java.lang.String name) {
		return new cn.hg.jooq.tables.Test(name, null);
	}
}
