/**
 * This class is generated by jOOQ
 */
package cn.hg.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TGoods extends org.jooq.impl.TableImpl<cn.hg.jooq.tables.records.TGoodsRecord> {

	private static final long serialVersionUID = 2083433660;

	/**
	 * The singleton instance of <code>test.t_goods</code>
	 */
	public static final cn.hg.jooq.tables.TGoods T_GOODS = new cn.hg.jooq.tables.TGoods();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<cn.hg.jooq.tables.records.TGoodsRecord> getRecordType() {
		return cn.hg.jooq.tables.records.TGoodsRecord.class;
	}

	/**
	 * The column <code>test.t_goods.id</code>.
	 */
	public final org.jooq.TableField<cn.hg.jooq.tables.records.TGoodsRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>test.t_goods.name</code>.
	 */
	public final org.jooq.TableField<cn.hg.jooq.tables.records.TGoodsRecord, java.lang.String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(45), this, "");

	/**
	 * The column <code>test.t_goods.count</code>.
	 */
	public final org.jooq.TableField<cn.hg.jooq.tables.records.TGoodsRecord, java.lang.Integer> COUNT = createField("count", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>test.t_goods.price</code>.
	 */
	public final org.jooq.TableField<cn.hg.jooq.tables.records.TGoodsRecord, java.lang.Double> PRICE = createField("price", org.jooq.impl.SQLDataType.DOUBLE, this, "");

	/**
	 * The column <code>test.t_goods.user_id</code>.
	 */
	public final org.jooq.TableField<cn.hg.jooq.tables.records.TGoodsRecord, java.lang.Integer> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * Create a <code>test.t_goods</code> table reference
	 */
	public TGoods() {
		this("t_goods", null);
	}

	/**
	 * Create an aliased <code>test.t_goods</code> table reference
	 */
	public TGoods(java.lang.String alias) {
		this(alias, cn.hg.jooq.tables.TGoods.T_GOODS);
	}

	private TGoods(java.lang.String alias, org.jooq.Table<cn.hg.jooq.tables.records.TGoodsRecord> aliased) {
		this(alias, aliased, null);
	}

	private TGoods(java.lang.String alias, org.jooq.Table<cn.hg.jooq.tables.records.TGoodsRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, cn.hg.jooq.Test.TEST, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<cn.hg.jooq.tables.records.TGoodsRecord, java.lang.Integer> getIdentity() {
		return cn.hg.jooq.Keys.IDENTITY_T_GOODS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<cn.hg.jooq.tables.records.TGoodsRecord> getPrimaryKey() {
		return cn.hg.jooq.Keys.KEY_T_GOODS_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<cn.hg.jooq.tables.records.TGoodsRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<cn.hg.jooq.tables.records.TGoodsRecord>>asList(cn.hg.jooq.Keys.KEY_T_GOODS_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public cn.hg.jooq.tables.TGoods as(java.lang.String alias) {
		return new cn.hg.jooq.tables.TGoods(alias, this);
	}

	/**
	 * Rename this table
	 */
	public cn.hg.jooq.tables.TGoods rename(java.lang.String name) {
		return new cn.hg.jooq.tables.TGoods(name, null);
	}
}
