/**
 * This class is generated by jOOQ
 */
package cn.hg.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TUser extends org.jooq.impl.TableImpl<cn.hg.jooq.tables.records.TUserRecord> {

	private static final long serialVersionUID = 1628579571;

	/**
	 * The singleton instance of <code>test.t_user</code>
	 */
	public static final cn.hg.jooq.tables.TUser T_USER = new cn.hg.jooq.tables.TUser();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<cn.hg.jooq.tables.records.TUserRecord> getRecordType() {
		return cn.hg.jooq.tables.records.TUserRecord.class;
	}

	/**
	 * The column <code>test.t_user.id</code>.
	 */
	public final org.jooq.TableField<cn.hg.jooq.tables.records.TUserRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>test.t_user.name</code>.
	 */
	public final org.jooq.TableField<cn.hg.jooq.tables.records.TUserRecord, java.lang.String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(45), this, "");

	/**
	 * The column <code>test.t_user.password</code>.
	 */
	public final org.jooq.TableField<cn.hg.jooq.tables.records.TUserRecord, java.lang.String> PASSWORD = createField("password", org.jooq.impl.SQLDataType.VARCHAR.length(45), this, "");

	/**
	 * The column <code>test.t_user.sex</code>.
	 */
	public final org.jooq.TableField<cn.hg.jooq.tables.records.TUserRecord, java.lang.Byte> SEX = createField("sex", org.jooq.impl.SQLDataType.TINYINT, this, "");

	/**
	 * Create a <code>test.t_user</code> table reference
	 */
	public TUser() {
		this("t_user", null);
	}

	/**
	 * Create an aliased <code>test.t_user</code> table reference
	 */
	public TUser(java.lang.String alias) {
		this(alias, cn.hg.jooq.tables.TUser.T_USER);
	}

	private TUser(java.lang.String alias, org.jooq.Table<cn.hg.jooq.tables.records.TUserRecord> aliased) {
		this(alias, aliased, null);
	}

	private TUser(java.lang.String alias, org.jooq.Table<cn.hg.jooq.tables.records.TUserRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, cn.hg.jooq.Test.TEST, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<cn.hg.jooq.tables.records.TUserRecord, java.lang.Integer> getIdentity() {
		return cn.hg.jooq.Keys.IDENTITY_T_USER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<cn.hg.jooq.tables.records.TUserRecord> getPrimaryKey() {
		return cn.hg.jooq.Keys.KEY_T_USER_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<cn.hg.jooq.tables.records.TUserRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<cn.hg.jooq.tables.records.TUserRecord>>asList(cn.hg.jooq.Keys.KEY_T_USER_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public cn.hg.jooq.tables.TUser as(java.lang.String alias) {
		return new cn.hg.jooq.tables.TUser(alias, this);
	}

	/**
	 * Rename this table
	 */
	public cn.hg.jooq.tables.TUser rename(java.lang.String name) {
		return new cn.hg.jooq.tables.TUser(name, null);
	}
}
