/**
 * This class is generated by jOOQ
 */
package cn.hg.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ConfigRecord extends org.jooq.impl.UpdatableRecordImpl<cn.hg.jooq.tables.records.ConfigRecord> implements org.jooq.Record5<java.lang.Integer, java.lang.String, cn.hg.constant.ConstantGenerator.Constant, java.lang.String, java.lang.Integer> {

	private static final long serialVersionUID = -586327719;

	/**
	 * Setter for <code>hg.config.id</code>.
	 */
	public void setId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>hg.config.id</code>.
	 */
	public java.lang.Integer getId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>hg.config.name</code>.
	 */
	public void setName(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>hg.config.name</code>.
	 */
	public java.lang.String getName() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>hg.config.type</code>.
	 */
	public void setType(cn.hg.constant.ConstantGenerator.Constant value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>hg.config.type</code>.
	 */
	public cn.hg.constant.ConstantGenerator.Constant getType() {
		return (cn.hg.constant.ConstantGenerator.Constant) getValue(2);
	}

	/**
	 * Setter for <code>hg.config.content</code>.
	 */
	public void setContent(java.lang.String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>hg.config.content</code>.
	 */
	public java.lang.String getContent() {
		return (java.lang.String) getValue(3);
	}

	/**
	 * Setter for <code>hg.config.description_id</code>.
	 */
	public void setDescriptionId(java.lang.Integer value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>hg.config.description_id</code>.
	 */
	public java.lang.Integer getDescriptionId() {
		return (java.lang.Integer) getValue(4);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record5 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row5<java.lang.Integer, java.lang.String, cn.hg.constant.ConstantGenerator.Constant, java.lang.String, java.lang.Integer> fieldsRow() {
		return (org.jooq.Row5) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row5<java.lang.Integer, java.lang.String, cn.hg.constant.ConstantGenerator.Constant, java.lang.String, java.lang.Integer> valuesRow() {
		return (org.jooq.Row5) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return cn.hg.jooq.tables.Config.CONFIG.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return cn.hg.jooq.tables.Config.CONFIG.NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<cn.hg.constant.ConstantGenerator.Constant> field3() {
		return cn.hg.jooq.tables.Config.CONFIG.TYPE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return cn.hg.jooq.tables.Config.CONFIG.CONTENT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field5() {
		return cn.hg.jooq.tables.Config.CONFIG.DESCRIPTION_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public cn.hg.constant.ConstantGenerator.Constant value3() {
		return getType();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getContent();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value5() {
		return getDescriptionId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ConfigRecord value1(java.lang.Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ConfigRecord value2(java.lang.String value) {
		setName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ConfigRecord value3(cn.hg.constant.ConstantGenerator.Constant value) {
		setType(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ConfigRecord value4(java.lang.String value) {
		setContent(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ConfigRecord value5(java.lang.Integer value) {
		setDescriptionId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ConfigRecord values(java.lang.Integer value1, java.lang.String value2, cn.hg.constant.ConstantGenerator.Constant value3, java.lang.String value4, java.lang.Integer value5) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached ConfigRecord
	 */
	public ConfigRecord() {
		super(cn.hg.jooq.tables.Config.CONFIG);
	}

	/**
	 * Create a detached, initialised ConfigRecord
	 */
	public ConfigRecord(java.lang.Integer id, java.lang.String name, cn.hg.constant.ConstantGenerator.Constant type, java.lang.String content, java.lang.Integer descriptionId) {
		super(cn.hg.jooq.tables.Config.CONFIG);

		setValue(0, id);
		setValue(1, name);
		setValue(2, type);
		setValue(3, content);
		setValue(4, descriptionId);
	}
}
