/**
 * This class is generated by jOOQ
 */
package cn.hg.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DescriptionRecord extends org.jooq.impl.UpdatableRecordImpl<cn.hg.jooq.tables.records.DescriptionRecord> implements org.jooq.Record3<java.lang.Integer, java.lang.String, cn.hg.constant.ConstantGenerator.Constant> {

	private static final long serialVersionUID = 1796859696;

	/**
	 * Setter for <code>hg.description.id</code>. 通用描述信息
	 */
	public void setId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>hg.description.id</code>. 通用描述信息
	 */
	public java.lang.Integer getId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>hg.description.text</code>.
	 */
	public void setText(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>hg.description.text</code>.
	 */
	public java.lang.String getText() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>hg.description.type</code>.
	 */
	public void setType(cn.hg.constant.ConstantGenerator.Constant value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>hg.description.type</code>.
	 */
	public cn.hg.constant.ConstantGenerator.Constant getType() {
		return (cn.hg.constant.ConstantGenerator.Constant) getValue(2);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record3 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<java.lang.Integer, java.lang.String, cn.hg.constant.ConstantGenerator.Constant> fieldsRow() {
		return (org.jooq.Row3) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<java.lang.Integer, java.lang.String, cn.hg.constant.ConstantGenerator.Constant> valuesRow() {
		return (org.jooq.Row3) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return cn.hg.jooq.tables.Description.DESCRIPTION.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return cn.hg.jooq.tables.Description.DESCRIPTION.TEXT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<cn.hg.constant.ConstantGenerator.Constant> field3() {
		return cn.hg.jooq.tables.Description.DESCRIPTION.TYPE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getText();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public cn.hg.constant.ConstantGenerator.Constant value3() {
		return getType();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DescriptionRecord value1(java.lang.Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DescriptionRecord value2(java.lang.String value) {
		setText(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DescriptionRecord value3(cn.hg.constant.ConstantGenerator.Constant value) {
		setType(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DescriptionRecord values(java.lang.Integer value1, java.lang.String value2, cn.hg.constant.ConstantGenerator.Constant value3) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached DescriptionRecord
	 */
	public DescriptionRecord() {
		super(cn.hg.jooq.tables.Description.DESCRIPTION);
	}

	/**
	 * Create a detached, initialised DescriptionRecord
	 */
	public DescriptionRecord(java.lang.Integer id, java.lang.String text, cn.hg.constant.ConstantGenerator.Constant type) {
		super(cn.hg.jooq.tables.Description.DESCRIPTION);

		setValue(0, id);
		setValue(1, text);
		setValue(2, type);
	}
}
