/**
 * This class is generated by jOOQ
 */
package cn.hg.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ExampleGroupRecord extends org.jooq.impl.TableRecordImpl<cn.hg.jooq.tables.records.ExampleGroupRecord> implements org.jooq.Record2<java.lang.Integer, java.lang.Integer> {

	private static final long serialVersionUID = 206283662;

	/**
	 * Setter for <code>hg.example_group.picture_id</code>.
	 */
	public void setPictureId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>hg.example_group.picture_id</code>.
	 */
	public java.lang.Integer getPictureId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>hg.example_group.example_id</code>.
	 */
	public void setExampleId(java.lang.Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>hg.example_group.example_id</code>.
	 */
	public java.lang.Integer getExampleId() {
		return (java.lang.Integer) getValue(1);
	}

	// -------------------------------------------------------------------------
	// Record2 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row2<java.lang.Integer, java.lang.Integer> fieldsRow() {
		return (org.jooq.Row2) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row2<java.lang.Integer, java.lang.Integer> valuesRow() {
		return (org.jooq.Row2) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return cn.hg.jooq.tables.ExampleGroup.EXAMPLE_GROUP.PICTURE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field2() {
		return cn.hg.jooq.tables.ExampleGroup.EXAMPLE_GROUP.EXAMPLE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getPictureId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value2() {
		return getExampleId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ExampleGroupRecord value1(java.lang.Integer value) {
		setPictureId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ExampleGroupRecord value2(java.lang.Integer value) {
		setExampleId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ExampleGroupRecord values(java.lang.Integer value1, java.lang.Integer value2) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached ExampleGroupRecord
	 */
	public ExampleGroupRecord() {
		super(cn.hg.jooq.tables.ExampleGroup.EXAMPLE_GROUP);
	}

	/**
	 * Create a detached, initialised ExampleGroupRecord
	 */
	public ExampleGroupRecord(java.lang.Integer pictureId, java.lang.Integer exampleId) {
		super(cn.hg.jooq.tables.ExampleGroup.EXAMPLE_GROUP);

		setValue(0, pictureId);
		setValue(1, exampleId);
	}
}
