/**
 * This class is generated by jOOQ
 */
package cn.hg.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GroupRecord extends org.jooq.impl.UpdatableRecordImpl<cn.hg.jooq.tables.records.GroupRecord> implements org.jooq.Record4<java.lang.Integer, java.lang.String, java.lang.Integer, java.sql.Timestamp> {

	private static final long serialVersionUID = -519555850;

	/**
	 * Setter for <code>hg.group.id</code>.
	 */
	public void setId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>hg.group.id</code>.
	 */
	public java.lang.Integer getId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>hg.group.name</code>.
	 */
	public void setName(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>hg.group.name</code>.
	 */
	public java.lang.String getName() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>hg.group.description_id</code>.
	 */
	public void setDescriptionId(java.lang.Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>hg.group.description_id</code>.
	 */
	public java.lang.Integer getDescriptionId() {
		return (java.lang.Integer) getValue(2);
	}

	/**
	 * Setter for <code>hg.group.time_stamp</code>.
	 */
	public void setTimeStamp(java.sql.Timestamp value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>hg.group.time_stamp</code>.
	 */
	public java.sql.Timestamp getTimeStamp() {
		return (java.sql.Timestamp) getValue(3);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record4 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row4<java.lang.Integer, java.lang.String, java.lang.Integer, java.sql.Timestamp> fieldsRow() {
		return (org.jooq.Row4) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row4<java.lang.Integer, java.lang.String, java.lang.Integer, java.sql.Timestamp> valuesRow() {
		return (org.jooq.Row4) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return cn.hg.jooq.tables.Group.GROUP.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return cn.hg.jooq.tables.Group.GROUP.NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field3() {
		return cn.hg.jooq.tables.Group.GROUP.DESCRIPTION_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field4() {
		return cn.hg.jooq.tables.Group.GROUP.TIME_STAMP;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value3() {
		return getDescriptionId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value4() {
		return getTimeStamp();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public GroupRecord value1(java.lang.Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public GroupRecord value2(java.lang.String value) {
		setName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public GroupRecord value3(java.lang.Integer value) {
		setDescriptionId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public GroupRecord value4(java.sql.Timestamp value) {
		setTimeStamp(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public GroupRecord values(java.lang.Integer value1, java.lang.String value2, java.lang.Integer value3, java.sql.Timestamp value4) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached GroupRecord
	 */
	public GroupRecord() {
		super(cn.hg.jooq.tables.Group.GROUP);
	}

	/**
	 * Create a detached, initialised GroupRecord
	 */
	public GroupRecord(java.lang.Integer id, java.lang.String name, java.lang.Integer descriptionId, java.sql.Timestamp timeStamp) {
		super(cn.hg.jooq.tables.Group.GROUP);

		setValue(0, id);
		setValue(1, name);
		setValue(2, descriptionId);
		setValue(3, timeStamp);
	}
}
