/**
 * This class is generated by jOOQ
 */
package cn.hg.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ManagerRecord extends org.jooq.impl.UpdatableRecordImpl<cn.hg.jooq.tables.records.ManagerRecord> implements org.jooq.Record4<java.lang.Integer, java.lang.String, java.lang.String, cn.hg.constant.ConstantGenerator.Constant> {

	private static final long serialVersionUID = 2093348596;

	/**
	 * Setter for <code>hg.manager.id</code>. 账号表
	 */
	public void setId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>hg.manager.id</code>. 账号表
	 */
	public java.lang.Integer getId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>hg.manager.name</code>.
	 */
	public void setName(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>hg.manager.name</code>.
	 */
	public java.lang.String getName() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>hg.manager.password</code>.
	 */
	public void setPassword(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>hg.manager.password</code>.
	 */
	public java.lang.String getPassword() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>hg.manager.type</code>.
	 */
	public void setType(cn.hg.constant.ConstantGenerator.Constant value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>hg.manager.type</code>.
	 */
	public cn.hg.constant.ConstantGenerator.Constant getType() {
		return (cn.hg.constant.ConstantGenerator.Constant) getValue(3);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record4 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row4<java.lang.Integer, java.lang.String, java.lang.String, cn.hg.constant.ConstantGenerator.Constant> fieldsRow() {
		return (org.jooq.Row4) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row4<java.lang.Integer, java.lang.String, java.lang.String, cn.hg.constant.ConstantGenerator.Constant> valuesRow() {
		return (org.jooq.Row4) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return cn.hg.jooq.tables.Manager.MANAGER.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return cn.hg.jooq.tables.Manager.MANAGER.NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return cn.hg.jooq.tables.Manager.MANAGER.PASSWORD;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<cn.hg.constant.ConstantGenerator.Constant> field4() {
		return cn.hg.jooq.tables.Manager.MANAGER.TYPE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getPassword();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public cn.hg.constant.ConstantGenerator.Constant value4() {
		return getType();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ManagerRecord value1(java.lang.Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ManagerRecord value2(java.lang.String value) {
		setName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ManagerRecord value3(java.lang.String value) {
		setPassword(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ManagerRecord value4(cn.hg.constant.ConstantGenerator.Constant value) {
		setType(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ManagerRecord values(java.lang.Integer value1, java.lang.String value2, java.lang.String value3, cn.hg.constant.ConstantGenerator.Constant value4) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached ManagerRecord
	 */
	public ManagerRecord() {
		super(cn.hg.jooq.tables.Manager.MANAGER);
	}

	/**
	 * Create a detached, initialised ManagerRecord
	 */
	public ManagerRecord(java.lang.Integer id, java.lang.String name, java.lang.String password, cn.hg.constant.ConstantGenerator.Constant type) {
		super(cn.hg.jooq.tables.Manager.MANAGER);

		setValue(0, id);
		setValue(1, name);
		setValue(2, password);
		setValue(3, type);
	}
}
