/**
 * This class is generated by jOOQ
 */
package cn.hg.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MessageRecord extends org.jooq.impl.UpdatableRecordImpl<cn.hg.jooq.tables.records.MessageRecord> implements org.jooq.Record7<java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.lang.String, cn.hg.constant.ConstantGenerator.Constant, java.sql.Timestamp> {

	private static final long serialVersionUID = 358392415;

	/**
	 * Setter for <code>hg.message.id</code>.
	 */
	public void setId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>hg.message.id</code>.
	 */
	public java.lang.Integer getId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>hg.message.name</code>.
	 */
	public void setName(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>hg.message.name</code>.
	 */
	public java.lang.String getName() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>hg.message.email</code>.
	 */
	public void setEmail(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>hg.message.email</code>.
	 */
	public java.lang.String getEmail() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>hg.message.phone</code>.
	 */
	public void setPhone(java.lang.String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>hg.message.phone</code>.
	 */
	public java.lang.String getPhone() {
		return (java.lang.String) getValue(3);
	}

	/**
	 * Setter for <code>hg.message.content</code>.
	 */
	public void setContent(java.lang.String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>hg.message.content</code>.
	 */
	public java.lang.String getContent() {
		return (java.lang.String) getValue(4);
	}

	/**
	 * Setter for <code>hg.message.status</code>.
	 */
	public void setStatus(cn.hg.constant.ConstantGenerator.Constant value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>hg.message.status</code>.
	 */
	public cn.hg.constant.ConstantGenerator.Constant getStatus() {
		return (cn.hg.constant.ConstantGenerator.Constant) getValue(5);
	}

	/**
	 * Setter for <code>hg.message.time_stamp</code>.
	 */
	public void setTimeStamp(java.sql.Timestamp value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>hg.message.time_stamp</code>.
	 */
	public java.sql.Timestamp getTimeStamp() {
		return (java.sql.Timestamp) getValue(6);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record7 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row7<java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.lang.String, cn.hg.constant.ConstantGenerator.Constant, java.sql.Timestamp> fieldsRow() {
		return (org.jooq.Row7) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row7<java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.lang.String, cn.hg.constant.ConstantGenerator.Constant, java.sql.Timestamp> valuesRow() {
		return (org.jooq.Row7) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return cn.hg.jooq.tables.Message.MESSAGE.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return cn.hg.jooq.tables.Message.MESSAGE.NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return cn.hg.jooq.tables.Message.MESSAGE.EMAIL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return cn.hg.jooq.tables.Message.MESSAGE.PHONE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field5() {
		return cn.hg.jooq.tables.Message.MESSAGE.CONTENT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<cn.hg.constant.ConstantGenerator.Constant> field6() {
		return cn.hg.jooq.tables.Message.MESSAGE.STATUS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field7() {
		return cn.hg.jooq.tables.Message.MESSAGE.TIME_STAMP;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getEmail();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getPhone();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value5() {
		return getContent();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public cn.hg.constant.ConstantGenerator.Constant value6() {
		return getStatus();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value7() {
		return getTimeStamp();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MessageRecord value1(java.lang.Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MessageRecord value2(java.lang.String value) {
		setName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MessageRecord value3(java.lang.String value) {
		setEmail(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MessageRecord value4(java.lang.String value) {
		setPhone(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MessageRecord value5(java.lang.String value) {
		setContent(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MessageRecord value6(cn.hg.constant.ConstantGenerator.Constant value) {
		setStatus(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MessageRecord value7(java.sql.Timestamp value) {
		setTimeStamp(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MessageRecord values(java.lang.Integer value1, java.lang.String value2, java.lang.String value3, java.lang.String value4, java.lang.String value5, cn.hg.constant.ConstantGenerator.Constant value6, java.sql.Timestamp value7) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached MessageRecord
	 */
	public MessageRecord() {
		super(cn.hg.jooq.tables.Message.MESSAGE);
	}

	/**
	 * Create a detached, initialised MessageRecord
	 */
	public MessageRecord(java.lang.Integer id, java.lang.String name, java.lang.String email, java.lang.String phone, java.lang.String content, cn.hg.constant.ConstantGenerator.Constant status, java.sql.Timestamp timeStamp) {
		super(cn.hg.jooq.tables.Message.MESSAGE);

		setValue(0, id);
		setValue(1, name);
		setValue(2, email);
		setValue(3, phone);
		setValue(4, content);
		setValue(5, status);
		setValue(6, timeStamp);
	}
}
