/**
 * This class is generated by jOOQ
 */
package cn.hg.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MobileDealRecord extends org.jooq.impl.TableRecordImpl<cn.hg.jooq.tables.records.MobileDealRecord> implements org.jooq.Record2<java.lang.String, java.lang.Integer> {

	private static final long serialVersionUID = 1750677038;

	/**
	 * Setter for <code>test.mobile_deal.mobile</code>.
	 */
	public void setMobile(java.lang.String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>test.mobile_deal.mobile</code>.
	 */
	public java.lang.String getMobile() {
		return (java.lang.String) getValue(0);
	}

	/**
	 * Setter for <code>test.mobile_deal.deal_id</code>.
	 */
	public void setDealId(java.lang.Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>test.mobile_deal.deal_id</code>.
	 */
	public java.lang.Integer getDealId() {
		return (java.lang.Integer) getValue(1);
	}

	// -------------------------------------------------------------------------
	// Record2 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row2<java.lang.String, java.lang.Integer> fieldsRow() {
		return (org.jooq.Row2) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row2<java.lang.String, java.lang.Integer> valuesRow() {
		return (org.jooq.Row2) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field1() {
		return cn.hg.jooq.tables.MobileDeal.MOBILE_DEAL.MOBILE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field2() {
		return cn.hg.jooq.tables.MobileDeal.MOBILE_DEAL.DEAL_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value1() {
		return getMobile();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value2() {
		return getDealId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MobileDealRecord value1(java.lang.String value) {
		setMobile(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MobileDealRecord value2(java.lang.Integer value) {
		setDealId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MobileDealRecord values(java.lang.String value1, java.lang.Integer value2) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached MobileDealRecord
	 */
	public MobileDealRecord() {
		super(cn.hg.jooq.tables.MobileDeal.MOBILE_DEAL);
	}

	/**
	 * Create a detached, initialised MobileDealRecord
	 */
	public MobileDealRecord(java.lang.String mobile, java.lang.Integer dealId) {
		super(cn.hg.jooq.tables.MobileDeal.MOBILE_DEAL);

		setValue(0, mobile);
		setValue(1, dealId);
	}
}
