/**
 * This class is generated by jOOQ
 */
package cn.hg.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TGoodsRecord extends org.jooq.impl.UpdatableRecordImpl<cn.hg.jooq.tables.records.TGoodsRecord> implements org.jooq.Record5<java.lang.Integer, java.lang.String, java.lang.Integer, java.lang.Double, java.lang.Integer> {

	private static final long serialVersionUID = 1090785239;

	/**
	 * Setter for <code>test.t_goods.id</code>.
	 */
	public void setId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>test.t_goods.id</code>.
	 */
	public java.lang.Integer getId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>test.t_goods.name</code>.
	 */
	public void setName(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>test.t_goods.name</code>.
	 */
	public java.lang.String getName() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>test.t_goods.count</code>.
	 */
	public void setCount(java.lang.Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>test.t_goods.count</code>.
	 */
	public java.lang.Integer getCount() {
		return (java.lang.Integer) getValue(2);
	}

	/**
	 * Setter for <code>test.t_goods.price</code>.
	 */
	public void setPrice(java.lang.Double value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>test.t_goods.price</code>.
	 */
	public java.lang.Double getPrice() {
		return (java.lang.Double) getValue(3);
	}

	/**
	 * Setter for <code>test.t_goods.user_id</code>.
	 */
	public void setUserId(java.lang.Integer value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>test.t_goods.user_id</code>.
	 */
	public java.lang.Integer getUserId() {
		return (java.lang.Integer) getValue(4);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record5 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row5<java.lang.Integer, java.lang.String, java.lang.Integer, java.lang.Double, java.lang.Integer> fieldsRow() {
		return (org.jooq.Row5) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row5<java.lang.Integer, java.lang.String, java.lang.Integer, java.lang.Double, java.lang.Integer> valuesRow() {
		return (org.jooq.Row5) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return cn.hg.jooq.tables.TGoods.T_GOODS.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return cn.hg.jooq.tables.TGoods.T_GOODS.NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field3() {
		return cn.hg.jooq.tables.TGoods.T_GOODS.COUNT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Double> field4() {
		return cn.hg.jooq.tables.TGoods.T_GOODS.PRICE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field5() {
		return cn.hg.jooq.tables.TGoods.T_GOODS.USER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value3() {
		return getCount();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Double value4() {
		return getPrice();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value5() {
		return getUserId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TGoodsRecord value1(java.lang.Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TGoodsRecord value2(java.lang.String value) {
		setName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TGoodsRecord value3(java.lang.Integer value) {
		setCount(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TGoodsRecord value4(java.lang.Double value) {
		setPrice(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TGoodsRecord value5(java.lang.Integer value) {
		setUserId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TGoodsRecord values(java.lang.Integer value1, java.lang.String value2, java.lang.Integer value3, java.lang.Double value4, java.lang.Integer value5) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached TGoodsRecord
	 */
	public TGoodsRecord() {
		super(cn.hg.jooq.tables.TGoods.T_GOODS);
	}

	/**
	 * Create a detached, initialised TGoodsRecord
	 */
	public TGoodsRecord(java.lang.Integer id, java.lang.String name, java.lang.Integer count, java.lang.Double price, java.lang.Integer userId) {
		super(cn.hg.jooq.tables.TGoods.T_GOODS);

		setValue(0, id);
		setValue(1, name);
		setValue(2, count);
		setValue(3, price);
		setValue(4, userId);
	}
}
