/**
 * This class is generated by jOOQ
 */
package cn.hg.jooq;

/**
 * This class is generated by jOOQ.
 *
 * A class modelling foreign key relationships between tables of the <code>test</code> 
 * schema
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

	// -------------------------------------------------------------------------
	// IDENTITY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.Identity<cn.hg.jooq.tables.records.TestRecord, java.lang.Integer> IDENTITY_TEST = Identities0.IDENTITY_TEST;
	public static final org.jooq.Identity<cn.hg.jooq.tables.records.TGoodsRecord, java.lang.Integer> IDENTITY_T_GOODS = Identities0.IDENTITY_T_GOODS;
	public static final org.jooq.Identity<cn.hg.jooq.tables.records.TUserRecord, java.lang.Integer> IDENTITY_T_USER = Identities0.IDENTITY_T_USER;

	// -------------------------------------------------------------------------
	// UNIQUE and PRIMARY KEY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.UniqueKey<cn.hg.jooq.tables.records.TestRecord> KEY_TEST_PRIMARY = UniqueKeys0.KEY_TEST_PRIMARY;
	public static final org.jooq.UniqueKey<cn.hg.jooq.tables.records.TGoodsRecord> KEY_T_GOODS_PRIMARY = UniqueKeys0.KEY_T_GOODS_PRIMARY;
	public static final org.jooq.UniqueKey<cn.hg.jooq.tables.records.TUserRecord> KEY_T_USER_PRIMARY = UniqueKeys0.KEY_T_USER_PRIMARY;

	// -------------------------------------------------------------------------
	// FOREIGN KEY definitions
	// -------------------------------------------------------------------------


	// -------------------------------------------------------------------------
	// [#1459] distribute members to avoid static initialisers > 64kb
	// -------------------------------------------------------------------------

	private static class Identities0 extends org.jooq.impl.AbstractKeys {
		public static org.jooq.Identity<cn.hg.jooq.tables.records.TestRecord, java.lang.Integer> IDENTITY_TEST = createIdentity(cn.hg.jooq.tables.Test.TEST, cn.hg.jooq.tables.Test.TEST.ID);
		public static org.jooq.Identity<cn.hg.jooq.tables.records.TGoodsRecord, java.lang.Integer> IDENTITY_T_GOODS = createIdentity(cn.hg.jooq.tables.TGoods.T_GOODS, cn.hg.jooq.tables.TGoods.T_GOODS.ID);
		public static org.jooq.Identity<cn.hg.jooq.tables.records.TUserRecord, java.lang.Integer> IDENTITY_T_USER = createIdentity(cn.hg.jooq.tables.TUser.T_USER, cn.hg.jooq.tables.TUser.T_USER.ID);
	}

	private static class UniqueKeys0 extends org.jooq.impl.AbstractKeys {
		public static final org.jooq.UniqueKey<cn.hg.jooq.tables.records.TestRecord> KEY_TEST_PRIMARY = createUniqueKey(cn.hg.jooq.tables.Test.TEST, cn.hg.jooq.tables.Test.TEST.ID);
		public static final org.jooq.UniqueKey<cn.hg.jooq.tables.records.TGoodsRecord> KEY_T_GOODS_PRIMARY = createUniqueKey(cn.hg.jooq.tables.TGoods.T_GOODS, cn.hg.jooq.tables.TGoods.T_GOODS.ID);
		public static final org.jooq.UniqueKey<cn.hg.jooq.tables.records.TUserRecord> KEY_T_USER_PRIMARY = createUniqueKey(cn.hg.jooq.tables.TUser.T_USER, cn.hg.jooq.tables.TUser.T_USER.ID);
	}
}
