/**
 * This class is generated by jOOQ
 */
package cn.hg.jooq;

/**
 * This class is generated by jOOQ.
 *
 * Convenience access to all tables in test
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table test.deal_ids
	 */
	public static final cn.hg.jooq.tables.DealIds DEAL_IDS = cn.hg.jooq.tables.DealIds.DEAL_IDS;

	/**
	 * The table test.mobile_deal
	 */
	public static final cn.hg.jooq.tables.MobileDeal MOBILE_DEAL = cn.hg.jooq.tables.MobileDeal.MOBILE_DEAL;

	/**
	 * The table test.test
	 */
	public static final cn.hg.jooq.tables.Test TEST = cn.hg.jooq.tables.Test.TEST;

	/**
	 * The table test.t_goods
	 */
	public static final cn.hg.jooq.tables.TGoods T_GOODS = cn.hg.jooq.tables.TGoods.T_GOODS;

	/**
	 * The table test.t_user
	 */
	public static final cn.hg.jooq.tables.TUser T_USER = cn.hg.jooq.tables.TUser.T_USER;
}
