/**
 * This class is generated by jOOQ
 */
package cn.hg.jooq;

/**
 * This class is generated by jOOQ.
 *
 * Convenience access to all tables in hg
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table hg.config
	 */
	public static final cn.hg.jooq.tables.Config CONFIG = cn.hg.jooq.tables.Config.CONFIG;

	/**
	 * The table hg.description
	 */
	public static final cn.hg.jooq.tables.Description DESCRIPTION = cn.hg.jooq.tables.Description.DESCRIPTION;

	/**
	 * The table hg.group
	 */
	public static final cn.hg.jooq.tables.Group GROUP = cn.hg.jooq.tables.Group.GROUP;

	/**
	 * The table hg.history
	 */
	public static final cn.hg.jooq.tables.History HISTORY = cn.hg.jooq.tables.History.HISTORY;

	/**
	 * The table hg.manager
	 */
	public static final cn.hg.jooq.tables.Manager MANAGER = cn.hg.jooq.tables.Manager.MANAGER;

	/**
	 * The table hg.message
	 */
	public static final cn.hg.jooq.tables.Message MESSAGE = cn.hg.jooq.tables.Message.MESSAGE;

	/**
	 * The table hg.picture
	 */
	public static final cn.hg.jooq.tables.Picture PICTURE = cn.hg.jooq.tables.Picture.PICTURE;

	/**
	 * The table hg.recruit
	 */
	public static final cn.hg.jooq.tables.Recruit RECRUIT = cn.hg.jooq.tables.Recruit.RECRUIT;
}
